export type Gender = 'male' | 'female';
export type Language = 'en' | 'es' | 'fr' | 'de' | 'it' | 'zh' | 'ja';

export interface NameEntry {
  gender: Gender;
  languages: Language[];
}

export const nameData: Record<string, NameEntry> = {
  // ── English male ──────────────────────────────────────────────────────────
  "james":      { gender: 'male',   languages: ['en'] },
  "john":       { gender: 'male',   languages: ['en'] },
  "robert":     { gender: 'male',   languages: ['en'] },
  "michael":    { gender: 'male',   languages: ['en', 'de'] },
  "william":    { gender: 'male',   languages: ['en'] },
  "david":      { gender: 'male',   languages: ['en', 'es'] },
  "richard":    { gender: 'male',   languages: ['en'] },
  "joseph":     { gender: 'male',   languages: ['en'] },
  "thomas":     { gender: 'male',   languages: ['en', 'fr'] },
  "charles":    { gender: 'male',   languages: ['en'] },
  "christopher":{ gender: 'male',   languages: ['en'] },
  "daniel":     { gender: 'male',   languages: ['en'] },
  "matthew":    { gender: 'male',   languages: ['en'] },
  "anthony":    { gender: 'male',   languages: ['en'] },
  "mark":       { gender: 'male',   languages: ['en'] },
  "donald":     { gender: 'male',   languages: ['en'] },
  "steven":     { gender: 'male',   languages: ['en'] },
  "paul":       { gender: 'male',   languages: ['en'] },
  "andrew":     { gender: 'male',   languages: ['en'] },
  "joshua":     { gender: 'male',   languages: ['en'] },
  "kenneth":    { gender: 'male',   languages: ['en'] },
  "kevin":      { gender: 'male',   languages: ['en'] },
  "brian":      { gender: 'male',   languages: ['en'] },
  "george":     { gender: 'male',   languages: ['en'] },
  "edward":     { gender: 'male',   languages: ['en'] },
  "ronald":     { gender: 'male',   languages: ['en'] },
  "timothy":    { gender: 'male',   languages: ['en'] },
  "jason":      { gender: 'male',   languages: ['en'] },
  "jeffrey":    { gender: 'male',   languages: ['en'] },
  "ryan":       { gender: 'male',   languages: ['en'] },
  "jacob":      { gender: 'male',   languages: ['en'] },
  "gary":       { gender: 'male',   languages: ['en'] },
  "nicholas":   { gender: 'male',   languages: ['en'] },
  "eric":       { gender: 'male',   languages: ['en', 'fr'] },
  "jonathan":   { gender: 'male',   languages: ['en'] },
  "stephen":    { gender: 'male',   languages: ['en'] },
  "larry":      { gender: 'male',   languages: ['en'] },
  "justin":     { gender: 'male',   languages: ['en'] },
  "scott":      { gender: 'male',   languages: ['en'] },
  "brandon":    { gender: 'male',   languages: ['en'] },
  "benjamin":   { gender: 'male',   languages: ['en', 'es'] },
  "samuel":     { gender: 'male',   languages: ['en'] },
  "raymond":    { gender: 'male',   languages: ['en'] },
  "gregory":    { gender: 'male',   languages: ['en'] },
  "frank":      { gender: 'male',   languages: ['en', 'de'] },
  "alexander":  { gender: 'male',   languages: ['en'] },
  "patrick":    { gender: 'male',   languages: ['en'] },
  "jack":       { gender: 'male',   languages: ['en'] },
  "dennis":     { gender: 'male',   languages: ['en'] },
  "jerry":      { gender: 'male',   languages: ['en'] },

  // English male nicknames
  "matt":       { gender: 'male',   languages: ['en'] },  // Matthew
  "bob":        { gender: 'male',   languages: ['en'] },  // Robert
  "rob":        { gender: 'male',   languages: ['en'] },  // Robert
  "bill":       { gender: 'male',   languages: ['en'] },  // William
  "will":       { gender: 'male',   languages: ['en'] },  // William
  "jim":        { gender: 'male',   languages: ['en'] },  // James
  "joe":        { gender: 'male',   languages: ['en'] },  // Joseph
  "tom":        { gender: 'male',   languages: ['en'] },  // Thomas
  "chris":      { gender: 'male',   languages: ['en'] },  // Christopher
  "dan":        { gender: 'male',   languages: ['en'] },  // Daniel
  "dave":       { gender: 'male',   languages: ['en'] },  // David
  "rick":       { gender: 'male',   languages: ['en'] },  // Richard
  "dick":       { gender: 'male',   languages: ['en'] },  // Richard
  "chuck":      { gender: 'male',   languages: ['en'] },  // Charles
  "charlie":    { gender: 'male',   languages: ['en'] },  // Charles
  "tony":       { gender: 'male',   languages: ['en'] },  // Anthony
  "mike":       { gender: 'male',   languages: ['en'] },  // Michael
  "don":        { gender: 'male',   languages: ['en'] },  // Donald
  "steve":      { gender: 'male',   languages: ['en'] },  // Steven
  "andy":       { gender: 'male',   languages: ['en'] },  // Andrew
  "josh":       { gender: 'male',   languages: ['en'] },  // Joshua
  "ken":        { gender: 'male',   languages: ['en'] },  // Kenneth
  "greg":       { gender: 'male',   languages: ['en'] },  // Gregory
  "ed":         { gender: 'male',   languages: ['en'] },  // Edward
  "ted":        { gender: 'male',   languages: ['en'] },  // Edward
  "ron":        { gender: 'male',   languages: ['en'] },  // Ronald
  "jeff":       { gender: 'male',   languages: ['en'] },  // Jeffrey
  "ben":        { gender: 'male',   languages: ['en'] },  // Benjamin
  "sam":        { gender: 'male',   languages: ['en'] },  // Samuel
  "nick":       { gender: 'male',   languages: ['en'] },  // Nicholas

  // ── English female ────────────────────────────────────────────────────────
  "mary":       { gender: 'female', languages: ['en'] },
  "patricia":   { gender: 'female', languages: ['en', 'es'] },
  "jennifer":   { gender: 'female', languages: ['en'] },
  "linda":      { gender: 'female', languages: ['en'] },
  "barbara":    { gender: 'female', languages: ['en'] },
  "elizabeth":  { gender: 'female', languages: ['en'] },
  "susan":      { gender: 'female', languages: ['en'] },
  "jessica":    { gender: 'female', languages: ['en'] },
  "sarah":      { gender: 'female', languages: ['en', 'fr', 'de'] },
  "karen":      { gender: 'female', languages: ['en'] },
  "lisa":       { gender: 'female', languages: ['en', 'de'] },
  "nancy":      { gender: 'female', languages: ['en'] },
  "betty":      { gender: 'female', languages: ['en'] },
  "margaret":   { gender: 'female', languages: ['en'] },
  "sandra":     { gender: 'female', languages: ['en'] },
  "ashley":     { gender: 'female', languages: ['en'] },
  "dorothy":    { gender: 'female', languages: ['en'] },
  "kimberly":   { gender: 'female', languages: ['en'] },
  "emily":      { gender: 'female', languages: ['en'] },
  "donna":      { gender: 'female', languages: ['en'] },
  "michelle":   { gender: 'female', languages: ['en'] },
  "carol":      { gender: 'female', languages: ['en'] },
  "amanda":     { gender: 'female', languages: ['en'] },
  "melissa":    { gender: 'female', languages: ['en'] },
  "deborah":    { gender: 'female', languages: ['en'] },
  "stephanie":  { gender: 'female', languages: ['en'] },
  "rebecca":    { gender: 'female', languages: ['en'] },
  "sharon":     { gender: 'female', languages: ['en'] },
  "laura":      { gender: 'female', languages: ['en', 'es', 'de'] },
  "cynthia":    { gender: 'female', languages: ['en'] },
  "kathleen":   { gender: 'female', languages: ['en'] },
  "amy":        { gender: 'female', languages: ['en'] },
  "angela":     { gender: 'female', languages: ['en'] },
  "shirley":    { gender: 'female', languages: ['en'] },
  "anna":       { gender: 'female', languages: ['en', 'de'] },
  "brenda":     { gender: 'female', languages: ['en'] },
  "pamela":     { gender: 'female', languages: ['en'] },
  "emma":       { gender: 'female', languages: ['en', 'fr'] },
  "nicole":     { gender: 'female', languages: ['en', 'de'] },
  "helen":      { gender: 'female', languages: ['en'] },
  "samantha":   { gender: 'female', languages: ['en'] },
  "katherine":  { gender: 'female', languages: ['en'] },
  "christine":  { gender: 'female', languages: ['en'] },
  "debra":      { gender: 'female', languages: ['en'] },
  "rachel":     { gender: 'female', languages: ['en'] },
  "carolyn":    { gender: 'female', languages: ['en'] },
  "janet":      { gender: 'female', languages: ['en'] },
  "catherine":  { gender: 'female', languages: ['en'] },
  "heather":    { gender: 'female', languages: ['en'] },
  "diane":      { gender: 'female', languages: ['en'] },

  // English female nicknames
  "pam":        { gender: 'female', languages: ['en'] },  // Pamela
  "liz":        { gender: 'female', languages: ['en'] },  // Elizabeth
  "beth":       { gender: 'female', languages: ['en'] },  // Elizabeth
  "sue":        { gender: 'female', languages: ['en'] },  // Susan
  "jess":       { gender: 'female', languages: ['en'] },  // Jessica
  "jen":        { gender: 'female', languages: ['en'] },  // Jennifer
  "barb":       { gender: 'female', languages: ['en'] },  // Barbara
  "deb":        { gender: 'female', languages: ['en'] },  // Deborah
  "debbie":     { gender: 'female', languages: ['en'] },  // Deborah
  "steph":      { gender: 'female', languages: ['en'] },  // Stephanie
  "becky":      { gender: 'female', languages: ['en'] },  // Rebecca
  "kathy":      { gender: 'female', languages: ['en'] },  // Kathleen
  "kate":       { gender: 'female', languages: ['en'] },  // Katherine
  "cathy":      { gender: 'female', languages: ['en'] },  // Catherine
  "sandy":      { gender: 'female', languages: ['en'] },  // Sandra
  "meg":        { gender: 'female', languages: ['en'] },  // Margaret
  "peggy":      { gender: 'female', languages: ['en'] },  // Margaret
  "maggie":     { gender: 'female', languages: ['en'] },  // Margaret
  "cindy":      { gender: 'female', languages: ['en'] },  // Cynthia
  "kim":        { gender: 'female', languages: ['en'] },  // Kimberly

  // ── Spanish male ──────────────────────────────────────────────────────────
  "juan":       { gender: 'male',   languages: ['es'] },
  "carlos":     { gender: 'male',   languages: ['es'] },
  "miguel":     { gender: 'male',   languages: ['es'] },
  "jose":       { gender: 'male',   languages: ['es'] },
  "luis":       { gender: 'male',   languages: ['es'] },
  "jorge":      { gender: 'male',   languages: ['es'] },
  "antonio":    { gender: 'male',   languages: ['es'] },
  "pedro":      { gender: 'male',   languages: ['es'] },
  "alejandro":  { gender: 'male',   languages: ['es'] },
  "manuel":     { gender: 'male',   languages: ['es'] },
  "diego":      { gender: 'male',   languages: ['es'] },
  "francisco":  { gender: 'male',   languages: ['es'] },
  "rafael":     { gender: 'male',   languages: ['es'] },
  "fernando":   { gender: 'male',   languages: ['es'] },
  "roberto":    { gender: 'male',   languages: ['es'] },
  "andres":     { gender: 'male',   languages: ['es'] },
  "felipe":     { gender: 'male',   languages: ['es'] },
  "ricardo":    { gender: 'male',   languages: ['es'] },
  "pablo":      { gender: 'male',   languages: ['es'] },
  "sergio":     { gender: 'male',   languages: ['es', 'it'] },
  "enrique":    { gender: 'male',   languages: ['es'] },
  "gabriel":    { gender: 'male',   languages: ['es', 'fr'] },
  "victor":     { gender: 'male',   languages: ['es'] },
  "javier":     { gender: 'male',   languages: ['es'] },
  "raul":       { gender: 'male',   languages: ['es'] },
  "gerardo":    { gender: 'male',   languages: ['es'] },
  "ernesto":    { gender: 'male',   languages: ['es'] },
  "marco":      { gender: 'male',   languages: ['es', 'it'] },
  "ivan":       { gender: 'male',   languages: ['es'] },
  "oscar":      { gender: 'male',   languages: ['es'] },
  "hector":     { gender: 'male',   languages: ['es'] },
  "arturo":     { gender: 'male',   languages: ['es'] },
  "rodolfo":    { gender: 'male',   languages: ['es'] },
  "armando":    { gender: 'male',   languages: ['es'] },
  "gustavo":    { gender: 'male',   languages: ['es'] },
  "cesar":      { gender: 'male',   languages: ['es'] },
  "ruben":      { gender: 'male',   languages: ['es'] },
  "ignacio":    { gender: 'male',   languages: ['es'] },
  "mauricio":   { gender: 'male',   languages: ['es'] },
  "rodrigo":    { gender: 'male',   languages: ['es'] },
  "jesus":      { gender: 'male',   languages: ['es'] },
  "santiago":   { gender: 'male',   languages: ['es'] },
  "adrian":     { gender: 'male',   languages: ['es'] },
  "esteban":    { gender: 'male',   languages: ['es'] },
  "nicolas":    { gender: 'male',   languages: ['es', 'fr'] },
  "alonso":     { gender: 'male',   languages: ['es'] },
  "alfredo":    { gender: 'male',   languages: ['es'] },
  "emilio":     { gender: 'male',   languages: ['es'] },

  // Spanish male nicknames
  "paco":       { gender: 'male',   languages: ['es'] },  // Francisco
  "pepe":       { gender: 'male',   languages: ['es'] },  // José
  "nacho":      { gender: 'male',   languages: ['es'] },  // Ignacio
  "tito":       { gender: 'male',   languages: ['es'] },  // various
  "beto":       { gender: 'male',   languages: ['es'] },  // Roberto/Alberto

  // ── Spanish female ────────────────────────────────────────────────────────
  "maria":      { gender: 'female', languages: ['es'] },
  "ana":        { gender: 'female', languages: ['es'] },
  "lucia":      { gender: 'female', languages: ['es', 'it'] },
  "carmen":     { gender: 'female', languages: ['es'] },
  "isabel":     { gender: 'female', languages: ['es'] },
  "sofia":      { gender: 'female', languages: ['es', 'it'] },
  "rosa":       { gender: 'female', languages: ['es', 'it'] },
  "elena":      { gender: 'female', languages: ['es'] },
  "pilar":      { gender: 'female', languages: ['es'] },
  "beatriz":    { gender: 'female', languages: ['es'] },
  "claudia":    { gender: 'female', languages: ['es', 'de'] },
  "adriana":    { gender: 'female', languages: ['es'] },
  "silvia":     { gender: 'female', languages: ['es'] },
  "veronica":   { gender: 'female', languages: ['es'] },
  "paula":      { gender: 'female', languages: ['es'] },
  "eva":        { gender: 'female', languages: ['es'] },
  "marta":      { gender: 'female', languages: ['es'] },
  "irene":      { gender: 'female', languages: ['es'] },
  "gloria":     { gender: 'female', languages: ['es'] },
  "nuria":      { gender: 'female', languages: ['es'] },
  "cristina":   { gender: 'female', languages: ['es'] },
  "fernanda":   { gender: 'female', languages: ['es'] },
  "andrea":     { gender: 'female', languages: ['es', 'de'] },
  "valentina":  { gender: 'female', languages: ['es', 'it'] },
  "mariana":    { gender: 'female', languages: ['es'] },
  "camila":     { gender: 'female', languages: ['es'] },
  "gabriela":   { gender: 'female', languages: ['es'] },
  "leticia":    { gender: 'female', languages: ['es'] },
  "rocio":      { gender: 'female', languages: ['es'] },
  "esperanza":  { gender: 'female', languages: ['es'] },
  "natalia":    { gender: 'female', languages: ['es'] },
  "rebeca":     { gender: 'female', languages: ['es'] },
  "consuelo":   { gender: 'female', languages: ['es'] },
  "concepcion": { gender: 'female', languages: ['es'] },
  "amparo":     { gender: 'female', languages: ['es'] },
  "dolores":    { gender: 'female', languages: ['es'] },
  "mercedes":   { gender: 'female', languages: ['es'] },
  "lourdes":    { gender: 'female', languages: ['es'] },
  "yolanda":    { gender: 'female', languages: ['es'] },
  "graciela":   { gender: 'female', languages: ['es'] },
  "alejandra":  { gender: 'female', languages: ['es'] },
  "alicia":     { gender: 'female', languages: ['es'] },
  "teresa":     { gender: 'female', languages: ['es'] },
  "nora":       { gender: 'female', languages: ['es'] },
  "esmeralda":  { gender: 'female', languages: ['es'] },
  "lorena":     { gender: 'female', languages: ['es'] },
  "miriam":     { gender: 'female', languages: ['es'] },
  "estrella":   { gender: 'female', languages: ['es'] },

  // Spanish female nicknames
  "lola":       { gender: 'female', languages: ['es'] },  // Dolores
  "concha":     { gender: 'female', languages: ['es'] },  // Concepción
  "lupe":       { gender: 'female', languages: ['es'] },  // Guadalupe
  "caro":       { gender: 'female', languages: ['es'] },  // Carolina/Carmen
  "ale":        { gender: 'female', languages: ['es'] },  // Alejandra

  // ── French male ───────────────────────────────────────────────────────────
  "pierre":     { gender: 'male',   languages: ['fr'] },
  "jean":       { gender: 'male',   languages: ['fr'] },
  "michel":     { gender: 'male',   languages: ['fr'] },
  "claude":     { gender: 'male',   languages: ['fr'] },
  "philippe":   { gender: 'male',   languages: ['fr'] },
  "alain":      { gender: 'male',   languages: ['fr'] },
  "bernard":    { gender: 'male',   languages: ['fr'] },
  "francois":   { gender: 'male',   languages: ['fr'] },
  "luc":        { gender: 'male',   languages: ['fr'] },
  "christophe": { gender: 'male',   languages: ['fr'] },
  "thierry":    { gender: 'male',   languages: ['fr'] },
  "olivier":    { gender: 'male',   languages: ['fr'] },
  "pascal":     { gender: 'male',   languages: ['fr'] },
  "gerard":     { gender: 'male',   languages: ['fr'] },
  "didier":     { gender: 'male',   languages: ['fr'] },
  "serge":      { gender: 'male',   languages: ['fr'] },
  "sylvain":    { gender: 'male',   languages: ['fr'] },
  "jerome":     { gender: 'male',   languages: ['fr'] },
  "patrice":    { gender: 'male',   languages: ['fr'] },
  "fabrice":    { gender: 'male',   languages: ['fr'] },
  "benoit":     { gender: 'male',   languages: ['fr'] },
  "gilles":     { gender: 'male',   languages: ['fr'] },
  "herve":      { gender: 'male',   languages: ['fr'] },
  "stephane":   { gender: 'male',   languages: ['fr'] },
  "yves":       { gender: 'male',   languages: ['fr'] },
  "julien":     { gender: 'male',   languages: ['fr'] },
  "romain":     { gender: 'male',   languages: ['fr'] },
  "florent":    { gender: 'male',   languages: ['fr'] },
  "maxime":     { gender: 'male',   languages: ['fr'] },
  "quentin":    { gender: 'male',   languages: ['fr'] },
  "clement":    { gender: 'male',   languages: ['fr'] },
  "baptiste":   { gender: 'male',   languages: ['fr'] },
  "antoine":    { gender: 'male',   languages: ['fr'] },
  "alexandre":  { gender: 'male',   languages: ['fr'] },
  "etienne":    { gender: 'male',   languages: ['fr'] },
  "mathieu":    { gender: 'male',   languages: ['fr'] },
  "arthur":     { gender: 'male',   languages: ['fr'] },
  "theo":       { gender: 'male',   languages: ['fr'] },
  "hugo":       { gender: 'male',   languages: ['fr'] },
  "lucas":      { gender: 'male',   languages: ['fr'] },
  "leo":        { gender: 'male',   languages: ['fr'] },
  "nathan":     { gender: 'male',   languages: ['fr'] },
  "axel":       { gender: 'male',   languages: ['fr'] },
  "raphael":    { gender: 'male',   languages: ['fr'] },
  "noah":       { gender: 'male',   languages: ['fr'] },
  "adam":       { gender: 'male',   languages: ['fr'] },

  // ── French female ─────────────────────────────────────────────────────────
  "marie":      { gender: 'female', languages: ['fr', 'de'] },
  "isabelle":   { gender: 'female', languages: ['fr'] },
  "nathalie":   { gender: 'female', languages: ['fr'] },
  "sylvie":     { gender: 'female', languages: ['fr'] },
  "valerie":    { gender: 'female', languages: ['fr'] },
  "sophie":     { gender: 'female', languages: ['fr', 'de'] },
  "helene":     { gender: 'female', languages: ['fr'] },
  "cecile":     { gender: 'female', languages: ['fr'] },
  "veronique":  { gender: 'female', languages: ['fr'] },
  "florence":   { gender: 'female', languages: ['fr'] },
  "brigitte":   { gender: 'female', languages: ['fr', 'de'] },
  "laurence":   { gender: 'female', languages: ['fr'] },
  "monique":    { gender: 'female', languages: ['fr'] },
  "pascale":    { gender: 'female', languages: ['fr'] },
  "genevieve":  { gender: 'female', languages: ['fr'] },
  "chantal":    { gender: 'female', languages: ['fr'] },
  "dominique":  { gender: 'female', languages: ['fr'] },
  "martine":    { gender: 'female', languages: ['fr'] },
  "aurelie":    { gender: 'female', languages: ['fr'] },
  "amelie":     { gender: 'female', languages: ['fr'] },
  "laure":      { gender: 'female', languages: ['fr'] },
  "juliette":   { gender: 'female', languages: ['fr'] },
  "camille":    { gender: 'female', languages: ['fr'] },
  "chloe":      { gender: 'female', languages: ['fr'] },
  "manon":      { gender: 'female', languages: ['fr'] },
  "lea":        { gender: 'female', languages: ['fr', 'de'] },
  "pauline":    { gender: 'female', languages: ['fr'] },
  "marine":     { gender: 'female', languages: ['fr'] },
  "jade":       { gender: 'female', languages: ['fr'] },
  "ines":       { gender: 'female', languages: ['fr'] },
  "lucie":      { gender: 'female', languages: ['fr'] },
  "alice":      { gender: 'female', languages: ['fr', 'it'] },
  "anaelle":    { gender: 'female', languages: ['fr'] },
  "zoe":        { gender: 'female', languages: ['fr'] },
  "clementine": { gender: 'female', languages: ['fr'] },
  "elise":      { gender: 'female', languages: ['fr'] },
  "oceane":     { gender: 'female', languages: ['fr'] },
  "margaux":    { gender: 'female', languages: ['fr'] },
  "mathilde":   { gender: 'female', languages: ['fr'] },
  "charlotte":  { gender: 'female', languages: ['fr'] },
  "clara":      { gender: 'female', languages: ['fr'] },
  "ophelie":    { gender: 'female', languages: ['fr'] },
  "elodie":     { gender: 'female', languages: ['fr'] },
  "emilie":     { gender: 'female', languages: ['fr'] },
  "anais":      { gender: 'female', languages: ['fr'] },
  "fanny":      { gender: 'female', languages: ['fr'] },
  "claire":     { gender: 'female', languages: ['fr'] },
  "elsa":       { gender: 'female', languages: ['fr'] },

  // ── German male ───────────────────────────────────────────────────────────
  "hans":       { gender: 'male',   languages: ['de'] },
  "kurt":       { gender: 'male',   languages: ['de'] },
  "werner":     { gender: 'male',   languages: ['de'] },
  "gerhard":    { gender: 'male',   languages: ['de'] },
  "heinz":      { gender: 'male',   languages: ['de'] },
  "helmut":     { gender: 'male',   languages: ['de'] },
  "dieter":     { gender: 'male',   languages: ['de'] },
  "horst":      { gender: 'male',   languages: ['de'] },
  "gunter":     { gender: 'male',   languages: ['de'] },
  "manfred":    { gender: 'male',   languages: ['de'] },
  "walter":     { gender: 'male',   languages: ['de'] },
  "rolf":       { gender: 'male',   languages: ['de'] },
  "gunther":    { gender: 'male',   languages: ['de'] },
  "otto":       { gender: 'male',   languages: ['de'] },
  "karl":       { gender: 'male',   languages: ['de'] },
  "fritz":      { gender: 'male',   languages: ['de'] },
  "rainer":     { gender: 'male',   languages: ['de'] },
  "ernst":      { gender: 'male',   languages: ['de'] },
  "wolf":       { gender: 'male',   languages: ['de'] },
  "jurgen":     { gender: 'male',   languages: ['de'] },
  "bernd":      { gender: 'male',   languages: ['de'] },
  "norbert":    { gender: 'male',   languages: ['de'] },
  "ulrich":     { gender: 'male',   languages: ['de'] },
  "detlef":     { gender: 'male',   languages: ['de'] },
  "christoph":  { gender: 'male',   languages: ['de'] },
  "stefan":     { gender: 'male',   languages: ['de'] },
  "andreas":    { gender: 'male',   languages: ['de'] },
  "peter":      { gender: 'male',   languages: ['de'] },
  "martin":     { gender: 'male',   languages: ['de'] },
  "markus":     { gender: 'male',   languages: ['de'] },
  "tobias":     { gender: 'male',   languages: ['de'] },
  "florian":    { gender: 'male',   languages: ['de'] },
  "christian":  { gender: 'male',   languages: ['de'] },
  "sebastian":  { gender: 'male',   languages: ['de'] },
  "jan":        { gender: 'male',   languages: ['de'] },
  "felix":      { gender: 'male',   languages: ['de'] },
  "lukas":      { gender: 'male',   languages: ['de'] },
  "max":        { gender: 'male',   languages: ['de'] },
  "moritz":     { gender: 'male',   languages: ['de'] },
  "leon":       { gender: 'male',   languages: ['de'] },
  "jonas":      { gender: 'male',   languages: ['de'] },
  "tim":        { gender: 'male',   languages: ['de'] },
  "luca":       { gender: 'male',   languages: ['de', 'it'] },
  "nico":       { gender: 'male',   languages: ['de'] },
  "simon":      { gender: 'male',   languages: ['de'] },
  "philipp":    { gender: 'male',   languages: ['de'] },
  "lennart":    { gender: 'male',   languages: ['de'] },
  "fabian":     { gender: 'male',   languages: ['de'] },

  // ── German female ─────────────────────────────────────────────────────────
  "hildegard":  { gender: 'female', languages: ['de'] },
  "gisela":     { gender: 'female', languages: ['de'] },
  "ursula":     { gender: 'female', languages: ['de'] },
  "helga":      { gender: 'female', languages: ['de'] },
  "renate":     { gender: 'female', languages: ['de'] },
  "gertrud":    { gender: 'female', languages: ['de'] },
  "ingrid":     { gender: 'female', languages: ['de'] },
  "christa":    { gender: 'female', languages: ['de'] },
  "monika":     { gender: 'female', languages: ['de'] },
  "marianne":   { gender: 'female', languages: ['de'] },
  "inge":       { gender: 'female', languages: ['de'] },
  "hannelore":  { gender: 'female', languages: ['de'] },
  "waltraud":   { gender: 'female', languages: ['de'] },
  "elfriede":   { gender: 'female', languages: ['de'] },
  "edeltraud":  { gender: 'female', languages: ['de'] },
  "brunhilde":  { gender: 'female', languages: ['de'] },
  "annegret":   { gender: 'female', languages: ['de'] },
  "ulrike":     { gender: 'female', languages: ['de'] },
  "heike":      { gender: 'female', languages: ['de'] },
  "petra":      { gender: 'female', languages: ['de'] },
  "sabine":     { gender: 'female', languages: ['de'] },
  "stefanie":   { gender: 'female', languages: ['de'] },
  "birgit":     { gender: 'female', languages: ['de'] },
  "anja":       { gender: 'female', languages: ['de'] },
  "kerstin":    { gender: 'female', languages: ['de'] },
  "katrin":     { gender: 'female', languages: ['de'] },
  "tanja":      { gender: 'female', languages: ['de'] },
  "susanne":    { gender: 'female', languages: ['de'] },
  "bettina":    { gender: 'female', languages: ['de'] },
  "lena":       { gender: 'female', languages: ['de'] },
  "julia":      { gender: 'female', languages: ['de'] },
  "hannah":     { gender: 'female', languages: ['de'] },
  "leonie":     { gender: 'female', languages: ['de'] },
  "luisa":      { gender: 'female', languages: ['de'] },
  "katharina":  { gender: 'female', languages: ['de'] },
  "mia":        { gender: 'female', languages: ['de'] },
  "jana":       { gender: 'female', languages: ['de'] },
  "franziska":  { gender: 'female', languages: ['de'] },
  "johanna":    { gender: 'female', languages: ['de'] },

  // ── Italian male ──────────────────────────────────────────────────────────
  "giancarlo":  { gender: 'male',   languages: ['it'] },
  "alessandro": { gender: 'male',   languages: ['it'] },
  "francesco":  { gender: 'male',   languages: ['it'] },
  "matteo":     { gender: 'male',   languages: ['it'] },
  "lorenzo":    { gender: 'male',   languages: ['it'] },
  "riccardo":   { gender: 'male',   languages: ['it'] },
  "filippo":    { gender: 'male',   languages: ['it'] },
  "stefano":    { gender: 'male',   languages: ['it'] },
  "giorgio":    { gender: 'male',   languages: ['it'] },
  "giovanni":   { gender: 'male',   languages: ['it'] },
  "giuseppe":   { gender: 'male',   languages: ['it'] },
  "luigi":      { gender: 'male',   languages: ['it'] },
  "mario":      { gender: 'male',   languages: ['it'] },
  "massimo":    { gender: 'male',   languages: ['it'] },
  "fabio":      { gender: 'male',   languages: ['it'] },
  "federico":   { gender: 'male',   languages: ['it'] },
  "leonardo":   { gender: 'male',   languages: ['it'] },
  "enzo":       { gender: 'male',   languages: ['it'] },
  "bruno":      { gender: 'male',   languages: ['it'] },
  "emanuele":   { gender: 'male',   languages: ['it'] },
  "nicola":     { gender: 'male',   languages: ['it'] },
  "claudio":    { gender: 'male',   languages: ['it'] },

  // Italian male nicknames
  "beppe":      { gender: 'male',   languages: ['it'] },  // Giuseppe
  "gigi":       { gender: 'male',   languages: ['it'] },  // Luigi/Gianluigi
  "nino":       { gender: 'male',   languages: ['it'] },  // Giovanni/Antonino
  "mino":       { gender: 'male',   languages: ['it'] },  // Domenico/Giacomo
  "sandro":     { gender: 'male',   languages: ['it'] },  // Alessandro

  // ── Italian female ────────────────────────────────────────────────────────
  "giulia":     { gender: 'female', languages: ['it'] },
  "aurora":     { gender: 'female', languages: ['it'] },
  "giorgia":    { gender: 'female', languages: ['it'] },
  "chiara":     { gender: 'female', languages: ['it'] },
  "martina":    { gender: 'female', languages: ['it'] },
  "francesca":  { gender: 'female', languages: ['it'] },
  "sara":       { gender: 'female', languages: ['it'] },
  "beatrice":   { gender: 'female', languages: ['it'] },
  "paola":      { gender: 'female', languages: ['it'] },
  "giovanna":   { gender: 'female', languages: ['it'] },
  "carla":      { gender: 'female', languages: ['it'] },
  "daniela":    { gender: 'female', languages: ['it'] },
  "ilaria":     { gender: 'female', languages: ['it'] },
  "monica":     { gender: 'female', languages: ['it'] },
  "sabrina":    { gender: 'female', languages: ['it'] },
  "patrizia":   { gender: 'female', languages: ['it'] },
  "antonella":  { gender: 'female', languages: ['it'] },
  "grazia":     { gender: 'female', languages: ['it'] },
  "gaia":       { gender: 'female', languages: ['it'] },
  "noemi":      { gender: 'female', languages: ['it'] },

  // Italian female nicknames
  "gia":        { gender: 'female', languages: ['it'] },  // Gianna/Giorgia
  "vale":       { gender: 'female', languages: ['it'] },  // Valentina
  "fran":       { gender: 'female', languages: ['it'] },  // Francesca
  "lulu":       { gender: 'female', languages: ['it'] },  // Lucia/Luisa
  "bea":        { gender: 'female', languages: ['it'] },  // Beatrice

  // ── Chinese male ──────────────────────────────────────────────────────────
  "wei":        { gender: 'male',   languages: ['zh'] },
  "yulong":     { gender: 'male',   languages: ['zh'] },
  "yong":       { gender: 'male',   languages: ['zh'] },
  "jian":       { gender: 'male',   languages: ['zh'] },
  "ming":       { gender: 'male',   languages: ['zh'] },
  "hao":        { gender: 'male',   languages: ['zh'] },
  "jun":        { gender: 'male',   languages: ['zh'] },
  "gang":       { gender: 'male',   languages: ['zh'] },
  "tao":        { gender: 'male',   languages: ['zh'] },
  "peng":       { gender: 'male',   languages: ['zh'] },
  "chao":       { gender: 'male',   languages: ['zh'] },
  "guang":      { gender: 'male',   languages: ['zh'] },
  "hui":        { gender: 'male',   languages: ['zh'] },
  "bo":         { gender: 'male',   languages: ['zh'] },
  "feng":       { gender: 'male',   languages: ['zh'] },
  "haoran":     { gender: 'male',   languages: ['zh'] },
  "zheng":      { gender: 'male',   languages: ['zh'] },
  "xiaolong":   { gender: 'male',   languages: ['zh'] },
  "weilong":    { gender: 'male',   languages: ['zh'] },
  "zichen":     { gender: 'male',   languages: ['zh'] },
  "junwei":     { gender: 'male',   languages: ['zh'] },
  "haoyang":    { gender: 'male',   languages: ['zh'] },
  "yuhao":      { gender: 'male',   languages: ['zh'] },
  "jianyu":     { gender: 'male',   languages: ['zh'] },
  "pengfei":    { gender: 'male',   languages: ['zh'] },
  "zijian":     { gender: 'male',   languages: ['zh'] },
  "wenbo":      { gender: 'male',   languages: ['zh'] },
  "jiahao":     { gender: 'male',   languages: ['zh'] },
  "mingkun":    { gender: 'male',   languages: ['zh'] },
  "wenhao":     { gender: 'male',   languages: ['zh'] },
  "kaijie":     { gender: 'male',   languages: ['zh'] },
  "zhihao":     { gender: 'male',   languages: ['zh'] },
  "guowei":     { gender: 'male',   languages: ['zh'] },
  "xiangjun":   { gender: 'male',   languages: ['zh'] },
  "jiaming":    { gender: 'male',   languages: ['zh'] },
  "yifeng":     { gender: 'male',   languages: ['zh'] },
  "qiang":      { gender: 'male',   languages: ['zh'] },
  "renwei":     { gender: 'male',   languages: ['zh'] },
  "bowen":      { gender: 'male',   languages: ['zh'] },
  "zhiyuan":    { gender: 'male',   languages: ['zh'] },
  "weicheng":   { gender: 'male',   languages: ['zh'] },
  "yuchen":     { gender: 'male',   languages: ['zh'] },
  "tianyu":     { gender: 'male',   languages: ['zh'] },
  "xudong":     { gender: 'male',   languages: ['zh'] },
  "haicheng":   { gender: 'male',   languages: ['zh'] },
  "guoqiang":   { gender: 'male',   languages: ['zh'] },
  "jianguo":    { gender: 'male',   languages: ['zh'] },
  "zhiwei":     { gender: 'male',   languages: ['zh'] },
  "mingzhi":    { gender: 'male',   languages: ['zh'] },
  "zhenyu":     { gender: 'male',   languages: ['zh'] },

  // ── Chinese female ────────────────────────────────────────────────────────
  "fang":       { gender: 'female', languages: ['zh'] },
  "xiu":        { gender: 'female', languages: ['zh'] },
  "yan":        { gender: 'female', languages: ['zh'] },
  "ling":       { gender: 'female', languages: ['zh'] },
  "yun":        { gender: 'female', languages: ['zh'] },
  "xia":        { gender: 'female', languages: ['zh'] },
  "hong":       { gender: 'female', languages: ['zh'] },
  "jing":       { gender: 'female', languages: ['zh'] },
  "ping":       { gender: 'female', languages: ['zh'] },
  "mei":        { gender: 'female', languages: ['zh'] },
  "li":         { gender: 'female', languages: ['zh'] },
  "qing":       { gender: 'female', languages: ['zh'] },
  "lan":        { gender: 'female', languages: ['zh'] },
  "yu":         { gender: 'female', languages: ['zh'] },
  "zhen":       { gender: 'female', languages: ['zh'] },
  "xiaoyan":    { gender: 'female', languages: ['zh'] },
  "yingying":   { gender: 'female', languages: ['zh'] },
  "tingting":   { gender: 'female', languages: ['zh'] },
  "wanying":    { gender: 'female', languages: ['zh'] },
  "xiaoling":   { gender: 'female', languages: ['zh'] },
  "jingyi":     { gender: 'female', languages: ['zh'] },
  "yuxin":      { gender: 'female', languages: ['zh'] },
  "meiying":    { gender: 'female', languages: ['zh'] },
  "lingling":   { gender: 'female', languages: ['zh'] },
  "xiaomei":    { gender: 'female', languages: ['zh'] },
  "yuhan":      { gender: 'female', languages: ['zh'] },
  "jiaying":    { gender: 'female', languages: ['zh'] },
  "mengmeng":   { gender: 'female', languages: ['zh'] },
  "yanyan":     { gender: 'female', languages: ['zh'] },
  "xuejiao":    { gender: 'female', languages: ['zh'] },
  "yiling":     { gender: 'female', languages: ['zh'] },
  "chunhua":    { gender: 'female', languages: ['zh'] },
  "xiuying":    { gender: 'female', languages: ['zh'] },
  "meiling":    { gender: 'female', languages: ['zh'] },
  "wenling":    { gender: 'female', languages: ['zh'] },
  "lianying":   { gender: 'female', languages: ['zh'] },
  "yanli":      { gender: 'female', languages: ['zh'] },
  "jingwen":    { gender: 'female', languages: ['zh'] },
  "xiulan":     { gender: 'female', languages: ['zh'] },
  "mingzhu":    { gender: 'female', languages: ['zh'] },
  "peipei":     { gender: 'female', languages: ['zh'] },
  "shanshan":   { gender: 'female', languages: ['zh'] },
  "mengqi":     { gender: 'female', languages: ['zh'] },
  "xinyi":      { gender: 'female', languages: ['zh'] },
  "wanqing":    { gender: 'female', languages: ['zh'] },
  "yumei":      { gender: 'female', languages: ['zh'] },
  "ruoxi":      { gender: 'female', languages: ['zh'] },
  "nuanyang":   { gender: 'female', languages: ['zh'] },
  "yilin":      { gender: 'female', languages: ['zh'] },
  "ziyi":       { gender: 'female', languages: ['zh'] },

  // ── Japanese male ─────────────────────────────────────────────────────────
  "hiroshi":    { gender: 'male',   languages: ['ja'] },
  "takeshi":    { gender: 'male',   languages: ['ja'] },
  "kenji":      { gender: 'male',   languages: ['ja'] },
  "ryoji":      { gender: 'male',   languages: ['ja'] },
  "kazuki":     { gender: 'male',   languages: ['ja'] },
  "daisuke":    { gender: 'male',   languages: ['ja'] },
  "naoki":      { gender: 'male',   languages: ['ja'] },
  "koji":       { gender: 'male',   languages: ['ja'] },
  "makoto":     { gender: 'male',   languages: ['ja'] },
  "ryota":      { gender: 'male',   languages: ['ja'] },
  "shota":      { gender: 'male',   languages: ['ja'] },
  "tatsuya":    { gender: 'male',   languages: ['ja'] },
  "yoshiki":    { gender: 'male',   languages: ['ja'] },
  "masato":     { gender: 'male',   languages: ['ja'] },
  "tomoya":     { gender: 'male',   languages: ['ja'] },
  "yuichi":     { gender: 'male',   languages: ['ja'] },
  "toshiki":    { gender: 'male',   languages: ['ja'] },
  "shinya":     { gender: 'male',   languages: ['ja'] },
  "kota":       { gender: 'male',   languages: ['ja'] },
  "daichi":     { gender: 'male',   languages: ['ja'] },
  "ryo":        { gender: 'male',   languages: ['ja'] },
  "sho":        { gender: 'male',   languages: ['ja'] },
  "yuto":       { gender: 'male',   languages: ['ja'] },
  "haruki":     { gender: 'male',   languages: ['ja'] },
  "sosuke":     { gender: 'male',   languages: ['ja'] },
  "kaito":      { gender: 'male',   languages: ['ja'] },
  "hayato":     { gender: 'male',   languages: ['ja'] },
  "ren":        { gender: 'male',   languages: ['ja'] },
  "sora":       { gender: 'male',   languages: ['ja'] },
  "tsubasa":    { gender: 'male',   languages: ['ja'] },
  "yuma":       { gender: 'male',   languages: ['ja'] },
  "ryusei":     { gender: 'male',   languages: ['ja'] },
  "sota":       { gender: 'male',   languages: ['ja'] },
  "kohei":      { gender: 'male',   languages: ['ja'] },
  "shohei":     { gender: 'male',   languages: ['ja'] },
  "masaki":     { gender: 'male',   languages: ['ja'] },
  "taiki":      { gender: 'male',   languages: ['ja'] },
  "yukito":     { gender: 'male',   languages: ['ja'] },
  "keita":      { gender: 'male',   languages: ['ja'] },
  "ryunosuke":  { gender: 'male',   languages: ['ja'] },
  "hinata":     { gender: 'male',   languages: ['ja'] },
  "akira":      { gender: 'male',   languages: ['ja'] },
  "isamu":      { gender: 'male',   languages: ['ja'] },
  "noboru":     { gender: 'male',   languages: ['ja'] },
  "satoshi":    { gender: 'male',   languages: ['ja'] },
  "shinji":     { gender: 'male',   languages: ['ja'] },
  "taro":       { gender: 'male',   languages: ['ja'] },
  "kazuya":     { gender: 'male',   languages: ['ja'] },
  "ichiro":     { gender: 'male',   languages: ['ja'] },
  "jiro":       { gender: 'male',   languages: ['ja'] },

  // ── Japanese female ───────────────────────────────────────────────────────
  "yuki":       { gender: 'female', languages: ['ja'] },
  "sakura":     { gender: 'female', languages: ['ja'] },
  "miku":       { gender: 'female', languages: ['ja'] },
  "aoi":        { gender: 'female', languages: ['ja'] },
  "rin":        { gender: 'female', languages: ['ja'] },
  "hana":       { gender: 'female', languages: ['ja'] },
  "nanami":     { gender: 'female', languages: ['ja'] },
  "emi":        { gender: 'female', languages: ['ja'] },
  "ayaka":      { gender: 'female', languages: ['ja'] },
  "mio":        { gender: 'female', languages: ['ja'] },
  "nana":       { gender: 'female', languages: ['ja'] },
  "risa":       { gender: 'female', languages: ['ja'] },
  "yuna":       { gender: 'female', languages: ['ja'] },
  "misaki":     { gender: 'female', languages: ['ja'] },
  "haruna":     { gender: 'female', languages: ['ja'] },
  "miho":       { gender: 'female', languages: ['ja'] },
  "saki":       { gender: 'female', languages: ['ja'] },
  "asuka":      { gender: 'female', languages: ['ja'] },
  "kana":       { gender: 'female', languages: ['ja'] },
  "koharu":     { gender: 'female', languages: ['ja'] },
  "momoka":     { gender: 'female', languages: ['ja'] },
  "akane":      { gender: 'female', languages: ['ja'] },
  "natsumi":    { gender: 'female', languages: ['ja'] },
  "yui":        { gender: 'female', languages: ['ja'] },
  "hazuki":     { gender: 'female', languages: ['ja'] },
  "mahiro":     { gender: 'female', languages: ['ja'] },
  "chiharu":    { gender: 'female', languages: ['ja'] },
  "fuuka":      { gender: 'female', languages: ['ja'] },
  "hinako":     { gender: 'female', languages: ['ja'] },
  "ichika":     { gender: 'female', languages: ['ja'] },
  "kanon":      { gender: 'female', languages: ['ja'] },
  "kotone":     { gender: 'female', languages: ['ja'] },
  "mana":       { gender: 'female', languages: ['ja'] },
  "nagisa":     { gender: 'female', languages: ['ja'] },
  "nozomi":     { gender: 'female', languages: ['ja'] },
  "reina":      { gender: 'female', languages: ['ja'] },
  "suzu":       { gender: 'female', languages: ['ja'] },
  "tomoka":     { gender: 'female', languages: ['ja'] },
  "tsukasa":    { gender: 'female', languages: ['ja'] },
  "umi":        { gender: 'female', languages: ['ja'] },
  "wakana":     { gender: 'female', languages: ['ja'] },
  "yayoi":      { gender: 'female', languages: ['ja'] },
  "yoshino":    { gender: 'female', languages: ['ja'] },
  "riko":       { gender: 'female', languages: ['ja'] },
  "erika":      { gender: 'female', languages: ['ja'] },
  "fumika":     { gender: 'female', languages: ['ja'] },
  "hikari":     { gender: 'female', languages: ['ja'] },
  "kokoro":     { gender: 'female', languages: ['ja'] },
  "kurumi":     { gender: 'female', languages: ['ja'] },
  "miyu":       { gender: 'female', languages: ['ja'] },
};
